// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzcknzqaxdqjflljofpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6Y2tuenFheGRxamZsbGpvZnBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNDEyMTksImV4cCI6MjA3MzcxNzIxOX0.Riei3HXHEkDsvPE7Q1Kcrnq5LgDv6geND_aKfNa9TsE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});